### ISSUE TITLE
How to read out the ClientID and Client_Secret for more functions?

### ISSUE THREAD

**Issue by Marow** [almatrass/passport-opskins#1]
How can i read out the ClientID and the Client_Secret for use more functions on the usersside like refresh_token?

Cause after 30 minutes my users "timeout" and i dont can grab any infos from opskins api...
Or do you have anything to "refresh" the user api over opskins? :/

Get everytime error "bearer invalid" after 30minutes on API Calls like that
`https://api-trade.opskins.com/ITrade/GetTradeURL/v1/`

**Comment by almatrass** [comment]
Hey,
I actually incorrectly documented that, OPSkins lets you POST `https://oauth.opskins.com/v1/access_token`, with `grant_type=refresh_token`, and the `refresh_token=YOUR_REFRESH_TOKEN`, which is found in `user.access.refresh_token`, like this:
```js
curl --request POST \
  --url https://oauth.opskins.com/v1/access_token \
  --header 'Authorization: Basic ZmYzNzFiMDQ1MzA3OiRuR3dZVmRhQEBQRXJLQVVwRyNrSFEmWUExTClBKlgx' \
  --data grant_type=refresh_token \
  --data refresh_token=6EnU6ZvGi5OoBcSpGs2V4PkcgfBgwr1V
```
This will give you a new `access_token` - valid for another 30 minutes. I'll add a method to the module to simplify this when I get a chance.
You can read more about that here: `https://docs.opskins.com/public/en.html#using-a-refresh-token`.
If you don't specify `permanent`, you'll need to get the user to login again to get a new `access_token`.

**Comment by almatrass** [comment]
Sorry I forgot you needed the Client ID and Client Secrets to do that, I've updated the module and added the method now: https://github.com/almatrass/passport-opskins#getting-a-new-access-token

**Comment by Marow** [comment]
Yeah i know. I tried now with that but its not correctly working :/ 

Would be very nice if you can update and create a function to update users access_token with the refresh_key :) 

It would be nice if you can do that soon/fast :) Where i can give you a little donation? :)

**Comment by Marow** [comment]
Nice thanks for the new function. 

But what is that?

This is my function i called when the error comes
`function refresh_user(socket, cb) {
	strat.refreshAccessToken(socket.request.session.passport.user.access.refresh_token, (err, token) => {
		if (err) return console.error(err);
    	socket.request.session.passport.user.access.access_token = token
		logger.info(socket.request.session.passport.user.id +' refreshed users access_token');
    	cb(true);
	});
}`

But when my callback sends back, i rerun my function where the error comes and run again, but than it "refreshed" the token again and again... every time.

When the first ` refreshed users access_token` comes, than it comes EVERY Round...

Do you know why or is that opskins bug? :/

**Comment by almatrass** [comment]
You're not overwriting the `access_token` in the user object then. That function you wrote won't overwrite the old access token.

I mean you could do something like
```js
function refresh_user(socket, cb) {
  strat.refreshAccessToken(socket.request.session.passport.user.access.refresh_token, (err, token) => {
    if (err) return cb(err);
    socket.request.session.passport.user.access.access_token = token;
    logger.info(socket.request.session.passport.user.id + ' refreshed users access_token');
    cb(null, socket);
  });
}

io.on('connection', socket => {
  refresh_user(socket, (err, newSocket) => {
    if (err) return console.error(err);
    
    socket = newSocket;
  });
});
```
But of course that would only stick for the current socket session.
You'll need to update your session store in your database for the new access token to be saved, but I'd recommend just storing the access tokens in a separate table in your database probably.

**Comment by Marow** [comment]
Oh okay, so the user looks to the old socket and not to a new one. I will test it 👍 

Why need to store that in database? I mean if the user logged out, i dont need the data and if he is logged in, i can read out of that socket

**Comment by almatrass** [comment]
Socket connections reset if the user refreshes the page, wouldn't be appropriate unless you have a single page application, even then it's kinda bad. 
You'll need to change the user's object in the database with your Session Store.

**Comment by Marow** [comment]
Dont understand :/

I have this now:

`request({
        headers: {
            'Authorization': 'Bearer '+socket.request.session.passport.user.access.access_token,
        },
        uri: 'https://api-trade.opskins.com/ITrade/GetTradeURL/v1/',
        method: 'GET'
    }, function(err, res, body) {
    	console.log('res');
    	console.log(res);
        var response = JSON.parse(body);
        if(response.error_description == 'Bearer token has expired') {
        	console.log('loadUserKeys ');
        	console.log(response)
        	console.log('loadUserKeys '+socket.request.session.passport.user.access.access_token);
        	refresh_user(socket, (err, newSocket) => {
				if (err) return console.error(err);
				if(newSocket) {
					socket = newSocket;
				}
			});
	        return;
        }
    }
);`

and this
`function refresh_user(socket, cb) {
	strat.refreshAccessToken(socket.request.session.passport.user.access.refresh_token, (err, token) => {
		if (err) return cb(err);
		socket.request.session.passport.user.access.access_token = token;
		logger.info(socket.request.session.passport.user.id + ' refreshed users access_token');
		cb(null, socket);
	});
}`

But when its first time token expired, than its every time...

Everytime that
`{ error: 'invalid_token',
  error_description: 'Bearer token has expired' }
loadUserKeys AQAA********************************************************Pw=
[2018-12-04T11:39:56.251] [INFO] default - 227186 refreshed users access_token
`
But only when i change the sites than... 

But why? I mean, i give the newSocket with calllback and set the newsocket to the old ones

**Comment by Marow** [comment]
Ahh i think i know what you mean now.

I dont need to save it in the socket, cause socket is new on every site.
I need to save that in an extra variable like "req.user" you have, for the user access things and not in the socket

**Comment by Marow** [comment]
Can i set a "main" variable that i can call in seperate functions or something?

In `app.get(/^\/auth\/opskins(\/return)?$/, passport.authenticate('opskins', {`
i can call "req.user.access" but how to call that in functions outside of any "app.get"

**Comment by Marow** [comment]
Okay thanks.

Than i will save that in the database and work with it 👍

**Comment by Marow** [comment]
Thanks! Its working now with saving in database and save it there 👍
