### ISSUE TITLE
Could you supply better error reporting?

### ISSUE THREAD

**Issue by iDefineHD** [almatrass/passport-opskins#2]
During my testing, i had no clue what the error was doing. it was a request error not being able to get the body. This would throw a generic error message. Could you maybe just tell the person to check that their api isn't disabled etc, or set up a case for that. Thanks.

**Comment by almatrass** [comment]
Hey,

Are you able to get the error again if you can and let me see so I can fix it.

Thanks

**Comment by iDefineHD** [comment]
it was the error thrown by `
      request.get(options, (err, response, body) => {
        if (err)
          return cb(err);
        if (!isValidJson(body))
          return cb(new Error(`Invalid JSON response`));
        let realBody = JSON.parse(body);
        if (realBody.status !== 1)
          return cb(new Error(`An error occurred`));
        cb(null, realBody.response.clients);
      });
};`
though.

**Comment by almatrass** [comment]
Oh yeah I'll change it so it gives the message sent by OPSkins too aha
