### ISSUE TITLE
Is there a way to use one API Key multiple times?

### ISSUE THREAD

**Issue by Marow** [almatrass/passport-opskins#3]
Hi, is there a chance to use one API Key multiple times? 

When i start two nodes for my Server, the first get Error:
`Failed to serialize user into session: invalid_client in index.js line 186`

or did you have an idea how to run the example index.js multiple times or something?
Cause if you have many users the emits will lagg and something :/

**Comment by almatrass** [comment]
Hello,

Sorry it took so long to fix this, I hadn't noticed the issue until now when I was forking apps and getting this error.

It's fixed now, the client details are stored locally and no clients get deleted.
